name: Create development builds

on:
  pull_request_labeld:
    branches: ['UAT']
    labels:
      - Test

jobs:
  ios_device_development_build:
    name: Build iOS device
    type: build
    params:
      platform: ios
      profile: development
  ios_simulator_development_build:
    name: Build iOS simulator
    type: build
    params:
      platform: ios
      profile: development-simulator
