name: Deploy to production

on:
  pull_request_labeled:
    branches: ['main']
    labels:
      - Production
jobs:
  build_ios:
    name: Build iOS
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: production
  submit_ios_build:
    name: Submit iOS Build
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
