name: Auto Merge Development to UAT

on:
  pull_request:
    branches:
      - UAT  # Runs when a PR is opened to UAT

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # Use Ubuntu for the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23  # Adjust based on your project

      - name: Install dependencies
        run: npm install  # Install dependencies

      - name: Run tests
        run: npm test  # Run your test suite

  merge:
    name: Merge Development to UAT
    needs: test  # Only runs if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full git history is fetched

      - name: Check for AUTO-MERGE keyword in PR body
        run: |
          PR_BODY=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_REF#refs/pull/}/files" | jq -r '.[0].body')
          if [[ "$PR_BODY" == *"AUTO-MERGE"* ]]; then
            echo "Merging development into UAT..."
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git checkout UAT
            git merge --no-ff development -m "Auto-merged development into UAT"
            git push origin UAT
          else
            echo "No AUTO-MERGE keyword found. Skipping merge."
            exit 0
          fi
